# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pycarl')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pycarl')
    _pycarl = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pycarl', [dirname(__file__)])
        except ImportError:
            import _pycarl
            return _pycarl
        try:
            _mod = imp.load_module('_pycarl', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _pycarl = swig_import_helper()
    del swig_import_helper
else:
    import _pycarl
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycarl.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pycarl.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pycarl.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pycarl.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pycarl.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pycarl.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pycarl.SwigPyIterator_copy(self)

    def next(self):
        return _pycarl.SwigPyIterator_next(self)

    def __next__(self):
        return _pycarl.SwigPyIterator___next__(self)

    def previous(self):
        return _pycarl.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pycarl.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pycarl.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pycarl.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pycarl.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pycarl.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pycarl.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pycarl.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pycarl.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _pycarl.SHARED_PTR_DISOWN
class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycarl.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycarl.vectori___nonzero__(self)

    def __bool__(self):
        return _pycarl.vectori___bool__(self)

    def __len__(self):
        return _pycarl.vectori___len__(self)

    def __getslice__(self, i, j):
        return _pycarl.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycarl.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycarl.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycarl.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycarl.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycarl.vectori___setitem__(self, *args)

    def pop(self):
        return _pycarl.vectori_pop(self)

    def append(self, x):
        return _pycarl.vectori_append(self, x)

    def empty(self):
        return _pycarl.vectori_empty(self)

    def size(self):
        return _pycarl.vectori_size(self)

    def swap(self, v):
        return _pycarl.vectori_swap(self, v)

    def begin(self):
        return _pycarl.vectori_begin(self)

    def end(self):
        return _pycarl.vectori_end(self)

    def rbegin(self):
        return _pycarl.vectori_rbegin(self)

    def rend(self):
        return _pycarl.vectori_rend(self)

    def clear(self):
        return _pycarl.vectori_clear(self)

    def get_allocator(self):
        return _pycarl.vectori_get_allocator(self)

    def pop_back(self):
        return _pycarl.vectori_pop_back(self)

    def erase(self, *args):
        return _pycarl.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _pycarl.new_vectori(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycarl.vectori_push_back(self, x)

    def front(self):
        return _pycarl.vectori_front(self)

    def back(self):
        return _pycarl.vectori_back(self)

    def assign(self, n, x):
        return _pycarl.vectori_assign(self, n, x)

    def resize(self, *args):
        return _pycarl.vectori_resize(self, *args)

    def insert(self, *args):
        return _pycarl.vectori_insert(self, *args)

    def reserve(self, n):
        return _pycarl.vectori_reserve(self, n)

    def capacity(self):
        return _pycarl.vectori_capacity(self)
    __swig_destroy__ = _pycarl.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _pycarl.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycarl.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycarl.vectord___nonzero__(self)

    def __bool__(self):
        return _pycarl.vectord___bool__(self)

    def __len__(self):
        return _pycarl.vectord___len__(self)

    def __getslice__(self, i, j):
        return _pycarl.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycarl.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycarl.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycarl.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycarl.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycarl.vectord___setitem__(self, *args)

    def pop(self):
        return _pycarl.vectord_pop(self)

    def append(self, x):
        return _pycarl.vectord_append(self, x)

    def empty(self):
        return _pycarl.vectord_empty(self)

    def size(self):
        return _pycarl.vectord_size(self)

    def swap(self, v):
        return _pycarl.vectord_swap(self, v)

    def begin(self):
        return _pycarl.vectord_begin(self)

    def end(self):
        return _pycarl.vectord_end(self)

    def rbegin(self):
        return _pycarl.vectord_rbegin(self)

    def rend(self):
        return _pycarl.vectord_rend(self)

    def clear(self):
        return _pycarl.vectord_clear(self)

    def get_allocator(self):
        return _pycarl.vectord_get_allocator(self)

    def pop_back(self):
        return _pycarl.vectord_pop_back(self)

    def erase(self, *args):
        return _pycarl.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _pycarl.new_vectord(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycarl.vectord_push_back(self, x)

    def front(self):
        return _pycarl.vectord_front(self)

    def back(self):
        return _pycarl.vectord_back(self)

    def assign(self, n, x):
        return _pycarl.vectord_assign(self, n, x)

    def resize(self, *args):
        return _pycarl.vectord_resize(self, *args)

    def insert(self, *args):
        return _pycarl.vectord_insert(self, *args)

    def reserve(self, n):
        return _pycarl.vectord_reserve(self, n)

    def capacity(self):
        return _pycarl.vectord_capacity(self)
    __swig_destroy__ = _pycarl.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _pycarl.vectord_swigregister
vectord_swigregister(vectord)

class vectorf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorf, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycarl.vectorf_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycarl.vectorf___nonzero__(self)

    def __bool__(self):
        return _pycarl.vectorf___bool__(self)

    def __len__(self):
        return _pycarl.vectorf___len__(self)

    def __getslice__(self, i, j):
        return _pycarl.vectorf___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycarl.vectorf___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycarl.vectorf___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycarl.vectorf___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycarl.vectorf___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycarl.vectorf___setitem__(self, *args)

    def pop(self):
        return _pycarl.vectorf_pop(self)

    def append(self, x):
        return _pycarl.vectorf_append(self, x)

    def empty(self):
        return _pycarl.vectorf_empty(self)

    def size(self):
        return _pycarl.vectorf_size(self)

    def swap(self, v):
        return _pycarl.vectorf_swap(self, v)

    def begin(self):
        return _pycarl.vectorf_begin(self)

    def end(self):
        return _pycarl.vectorf_end(self)

    def rbegin(self):
        return _pycarl.vectorf_rbegin(self)

    def rend(self):
        return _pycarl.vectorf_rend(self)

    def clear(self):
        return _pycarl.vectorf_clear(self)

    def get_allocator(self):
        return _pycarl.vectorf_get_allocator(self)

    def pop_back(self):
        return _pycarl.vectorf_pop_back(self)

    def erase(self, *args):
        return _pycarl.vectorf_erase(self, *args)

    def __init__(self, *args):
        this = _pycarl.new_vectorf(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycarl.vectorf_push_back(self, x)

    def front(self):
        return _pycarl.vectorf_front(self)

    def back(self):
        return _pycarl.vectorf_back(self)

    def assign(self, n, x):
        return _pycarl.vectorf_assign(self, n, x)

    def resize(self, *args):
        return _pycarl.vectorf_resize(self, *args)

    def insert(self, *args):
        return _pycarl.vectorf_insert(self, *args)

    def reserve(self, n):
        return _pycarl.vectorf_reserve(self, n)

    def capacity(self):
        return _pycarl.vectorf_capacity(self)
    __swig_destroy__ = _pycarl.delete_vectorf
    __del__ = lambda self: None
vectorf_swigregister = _pycarl.vectorf_swigregister
vectorf_swigregister(vectorf)

class vectorvf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorvf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorvf, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycarl.vectorvf_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycarl.vectorvf___nonzero__(self)

    def __bool__(self):
        return _pycarl.vectorvf___bool__(self)

    def __len__(self):
        return _pycarl.vectorvf___len__(self)

    def __getslice__(self, i, j):
        return _pycarl.vectorvf___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycarl.vectorvf___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycarl.vectorvf___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycarl.vectorvf___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycarl.vectorvf___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycarl.vectorvf___setitem__(self, *args)

    def pop(self):
        return _pycarl.vectorvf_pop(self)

    def append(self, x):
        return _pycarl.vectorvf_append(self, x)

    def empty(self):
        return _pycarl.vectorvf_empty(self)

    def size(self):
        return _pycarl.vectorvf_size(self)

    def swap(self, v):
        return _pycarl.vectorvf_swap(self, v)

    def begin(self):
        return _pycarl.vectorvf_begin(self)

    def end(self):
        return _pycarl.vectorvf_end(self)

    def rbegin(self):
        return _pycarl.vectorvf_rbegin(self)

    def rend(self):
        return _pycarl.vectorvf_rend(self)

    def clear(self):
        return _pycarl.vectorvf_clear(self)

    def get_allocator(self):
        return _pycarl.vectorvf_get_allocator(self)

    def pop_back(self):
        return _pycarl.vectorvf_pop_back(self)

    def erase(self, *args):
        return _pycarl.vectorvf_erase(self, *args)

    def __init__(self, *args):
        this = _pycarl.new_vectorvf(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycarl.vectorvf_push_back(self, x)

    def front(self):
        return _pycarl.vectorvf_front(self)

    def back(self):
        return _pycarl.vectorvf_back(self)

    def assign(self, n, x):
        return _pycarl.vectorvf_assign(self, n, x)

    def resize(self, *args):
        return _pycarl.vectorvf_resize(self, *args)

    def insert(self, *args):
        return _pycarl.vectorvf_insert(self, *args)

    def reserve(self, n):
        return _pycarl.vectorvf_reserve(self, n)

    def capacity(self):
        return _pycarl.vectorvf_capacity(self)
    __swig_destroy__ = _pycarl.delete_vectorvf
    __del__ = lambda self: None
vectorvf_swigregister = _pycarl.vectorvf_swigregister
vectorvf_swigregister(vectorvf)

SYN_FIXED = _pycarl.SYN_FIXED
SYN_PLASTIC = _pycarl.SYN_PLASTIC
TARGET_AMPA = _pycarl.TARGET_AMPA
TARGET_NMDA = _pycarl.TARGET_NMDA
UNKNOWN_NEURON = _pycarl.UNKNOWN_NEURON
POISSON_NEURON = _pycarl.POISSON_NEURON
TARGET_GABAa = _pycarl.TARGET_GABAa
TARGET_GABAb = _pycarl.TARGET_GABAb
TARGET_DA = _pycarl.TARGET_DA
TARGET_5HT = _pycarl.TARGET_5HT
TARGET_ACh = _pycarl.TARGET_ACh
TARGET_NE = _pycarl.TARGET_NE
INHIBITORY_NEURON = _pycarl.INHIBITORY_NEURON
EXCITATORY_NEURON = _pycarl.EXCITATORY_NEURON
DOPAMINERGIC_NEURON = _pycarl.DOPAMINERGIC_NEURON
EXCITATORY_POISSON = _pycarl.EXCITATORY_POISSON
INHIBITORY_POISSON = _pycarl.INHIBITORY_POISSON
ALL = _pycarl.ALL
ANY = _pycarl.ANY
EXP_CURVE = _pycarl.EXP_CURVE
PULSE_CURVE = _pycarl.PULSE_CURVE
TIMING_BASED_CURVE = _pycarl.TIMING_BASED_CURVE
UNKNOWN_CURVE = _pycarl.UNKNOWN_CURVE
CPU_CORES = _pycarl.CPU_CORES
GPU_CORES = _pycarl.GPU_CORES
STANDARD = _pycarl.STANDARD
DA_MOD = _pycarl.DA_MOD
UNKNOWN_STDP = _pycarl.UNKNOWN_STDP
COUNT = _pycarl.COUNT
AER = _pycarl.AER
CPU_MODE = _pycarl.CPU_MODE
GPU_MODE = _pycarl.GPU_MODE
HYBRID_MODE = _pycarl.HYBRID_MODE
USER = _pycarl.USER
DEVELOPER = _pycarl.DEVELOPER
SHOWTIME = _pycarl.SHOWTIME
SILENT = _pycarl.SILENT
CUSTOM = _pycarl.CUSTOM
UNKNOWN_LOGGER = _pycarl.UNKNOWN_LOGGER
NM_DA = _pycarl.NM_DA
NM_5HT = _pycarl.NM_5HT
NM_ACh = _pycarl.NM_ACh
NM_NE = _pycarl.NM_NE
NM_UNKNOWN = _pycarl.NM_UNKNOWN
INTERVAL_10MS = _pycarl.INTERVAL_10MS
INTERVAL_100MS = _pycarl.INTERVAL_100MS
INTERVAL_1000MS = _pycarl.INTERVAL_1000MS
CONFIG_STATE = _pycarl.CONFIG_STATE
SETUP_STATE = _pycarl.SETUP_STATE
RUN_STATE = _pycarl.RUN_STATE
CUBA = _pycarl.CUBA
COBA = _pycarl.COBA
NM4W_LN21 = _pycarl.NM4W_LN21
GPCR_NB14 = _pycarl.GPCR_NB14
DASEAC_CK09 = _pycarl.DASEAC_CK09
ACNE_ANCK12 = _pycarl.ACNE_ANCK12
ACNE_K12 = _pycarl.ACNE_K12
ACNE_K13 = _pycarl.ACNE_K13
D1D2_AK12 = _pycarl.D1D2_AK12
ACDA_BK19 = _pycarl.ACDA_BK19
alpha1_ADK13 = _pycarl.alpha1_ADK13
alpha2A_ADK13 = _pycarl.alpha2A_ADK13
D1_ADK13 = _pycarl.D1_ADK13
D2_AK15 = _pycarl.D2_AK15
UNKNOWN_ICALC = _pycarl.UNKNOWN_ICALC
class CARLsim(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CARLsim, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CARLsim, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycarl.new_CARLsim(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_CARLsim
    __del__ = lambda self: None

    def createSpikeGeneratorGroup(self, *args):
        return _pycarl.CARLsim_createSpikeGeneratorGroup(self, *args)

    def createGroup(self, *args):
        return _pycarl.CARLsim_createGroup(self, *args)

    def getNumSynapticConnections(self, connectionId):
        return _pycarl.CARLsim_getNumSynapticConnections(self, connectionId)

    def connect(self, *args):
        return _pycarl.CARLsim_connect(self, *args)

    def setConductances(self, *args):
        return _pycarl.CARLsim_setConductances(self, *args)

    def setNeuronParameters(self, grpId, izh_a, izh_b, izh_c, izh_d):
        return _pycarl.CARLsim_setNeuronParameters(self, grpId, izh_a, izh_b, izh_c, izh_d)

    def setSpikeRate(self, grpId, spikeRate, refPeriod=1):
        return _pycarl.CARLsim_setSpikeRate(self, grpId, spikeRate, refPeriod)

    def setConnectionMonitor(self, grpIdPre, grpIdPost, fname):
        return _pycarl.CARLsim_setConnectionMonitor(self, grpIdPre, grpIdPost, fname)

    def setGroupMonitor(self, grpId, fname):
        return _pycarl.CARLsim_setGroupMonitor(self, grpId, fname)

    def setSpikeMonitor(self, grpId, fileName):
        return _pycarl.CARLsim_setSpikeMonitor(self, grpId, fileName)

    def setHomeostasis(self, *args):
        return _pycarl.CARLsim_setHomeostasis(self, *args)

    def setHomeoBaseFiringRate(self, grpId, baseFiring, baseFiringSD=0.0):
        return _pycarl.CARLsim_setHomeoBaseFiringRate(self, grpId, baseFiring, baseFiringSD)

    def setNeuromodulator(self, grpId, baseDP, tauDP, base5HT, tau5HT, baseACh, tauACh, baseNE, tauNE):
        return _pycarl.CARLsim_setNeuromodulator(self, grpId, baseDP, tauDP, base5HT, tau5HT, baseACh, tauACh, baseNE, tauNE)

    def setSTDP(self, *args):
        return _pycarl.CARLsim_setSTDP(self, *args)

    def setESTDP(self, *args):
        return _pycarl.CARLsim_setESTDP(self, *args)

    def setISTDP(self, *args):
        return _pycarl.CARLsim_setISTDP(self, *args)

    def setSTP(self, *args):
        return _pycarl.CARLsim_setSTP(self, *args)

    def setWeightAndWeightChangeUpdate(self, wtANDwtChangeUpdateInterval, enableWtChangeDecay, wtChangeDecay=0.9):
        return _pycarl.CARLsim_setWeightAndWeightChangeUpdate(self, wtANDwtChangeUpdateInterval, enableWtChangeDecay, wtChangeDecay)

    def saveSimulation(self, fileName, saveSynapseInfo=True):
        return _pycarl.CARLsim_saveSimulation(self, fileName, saveSynapseInfo)

    def biasWeights(self, connId, bias, updateWeightRange=False):
        return _pycarl.CARLsim_biasWeights(self, connId, bias, updateWeightRange)

    def loadSimulation(self, fid):
        return _pycarl.CARLsim_loadSimulation(self, fid)

    def scaleWeights(self, connId, scale, updateWeightRange=False):
        return _pycarl.CARLsim_scaleWeights(self, connId, scale, updateWeightRange)

    def setExternalCurrent(self, *args):
        return _pycarl.CARLsim_setExternalCurrent(self, *args)

    def setSpikeGenerator(self, grpId, spikeGenFunc):
        return _pycarl.CARLsim_setSpikeGenerator(self, grpId, spikeGenFunc)

    def getSpikeMonitor(self, grpId):
        return _pycarl.CARLsim_getSpikeMonitor(self, grpId)

    def getSimTime(self):
        return _pycarl.CARLsim_getSimTime(self)

    def getSimTimeSec(self):
        return _pycarl.CARLsim_getSimTimeSec(self)

    def getSimTimeMsec(self):
        return _pycarl.CARLsim_getSimTimeMsec(self)

    def startTesting(self, updateWeights=True):
        return _pycarl.CARLsim_startTesting(self, updateWeights)

    def stopTesting(self):
        return _pycarl.CARLsim_stopTesting(self)

    def setupNetwork(self):
        return _pycarl.CARLsim_setupNetwork(self)

    def runNetwork(self, nSec, nMsec=0, printRunSummary=True):
        return _pycarl.CARLsim_runNetwork(self, nSec, nMsec, printRunSummary)
CARLsim_swigregister = _pycarl.CARLsim_swigregister
CARLsim_swigregister(CARLsim)

class PoissonRate(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PoissonRate, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PoissonRate, name)
    __repr__ = _swig_repr

    def __init__(self, nNeur, onGPU=False):
        this = _pycarl.new_PoissonRate(nNeur, onGPU)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_PoissonRate
    __del__ = lambda self: None

    def getNumNeurons(self):
        return _pycarl.PoissonRate_getNumNeurons(self)

    def getRate(self, neurId):
        return _pycarl.PoissonRate_getRate(self, neurId)

    def getRates(self):
        return _pycarl.PoissonRate_getRates(self)

    def setRate(self, neurId, rate):
        return _pycarl.PoissonRate_setRate(self, neurId, rate)

    def setRates(self, *args):
        return _pycarl.PoissonRate_setRates(self, *args)
PoissonRate_swigregister = _pycarl.PoissonRate_swigregister
PoissonRate_swigregister(PoissonRate)

class ConnectionMonitor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConnectionMonitor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ConnectionMonitor, name)
    __repr__ = _swig_repr

    def __init__(self, connMonCorePtr):
        this = _pycarl.new_ConnectionMonitor(connMonCorePtr)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_ConnectionMonitor
    __del__ = lambda self: None

    def calcWeightChanges(self):
        return _pycarl.ConnectionMonitor_calcWeightChanges(self)

    def getConnectId(self):
        return _pycarl.ConnectionMonitor_getConnectId(self)

    def getMaxWeight(self, getCurrent=False):
        return _pycarl.ConnectionMonitor_getMaxWeight(self, getCurrent)

    def getMinWeight(self, getCurrent=False):
        return _pycarl.ConnectionMonitor_getMinWeight(self, getCurrent)

    def getNumNeuronsPre(self):
        return _pycarl.ConnectionMonitor_getNumNeuronsPre(self)

    def getNumNeuronsPost(self):
        return _pycarl.ConnectionMonitor_getNumNeuronsPost(self)

    def getNumSynapses(self):
        return _pycarl.ConnectionMonitor_getNumSynapses(self)

    def getNumWeightsChanged(self, minAbsChanged=1e-5):
        return _pycarl.ConnectionMonitor_getNumWeightsChanged(self, minAbsChanged)

    def getNumWeightsInRange(self, minValue, maxValue):
        return _pycarl.ConnectionMonitor_getNumWeightsInRange(self, minValue, maxValue)

    def getNumWeightsWithValue(self, value):
        return _pycarl.ConnectionMonitor_getNumWeightsWithValue(self, value)

    def getPercentWeightsInRange(self, minValue, maxValue):
        return _pycarl.ConnectionMonitor_getPercentWeightsInRange(self, minValue, maxValue)

    def getPercentWeightsWithValue(self, value):
        return _pycarl.ConnectionMonitor_getPercentWeightsWithValue(self, value)

    def getPercentWeightsChanged(self, minAbsChanged=1e-5):
        return _pycarl.ConnectionMonitor_getPercentWeightsChanged(self, minAbsChanged)

    def getTimeMsCurrentSnapshot(self):
        return _pycarl.ConnectionMonitor_getTimeMsCurrentSnapshot(self)

    def getTimeMsLastSnapshot(self):
        return _pycarl.ConnectionMonitor_getTimeMsLastSnapshot(self)

    def getTimeMsSinceLastSnapshot(self):
        return _pycarl.ConnectionMonitor_getTimeMsSinceLastSnapshot(self)

    def getTotalAbsWeightChange(self):
        return _pycarl.ConnectionMonitor_getTotalAbsWeightChange(self)

    def _print(self):
        return _pycarl.ConnectionMonitor__print(self)

    def printSparse(self, neurPostId=-1, maxConn=100, connPerLine=4):
        return _pycarl.ConnectionMonitor_printSparse(self, neurPostId, maxConn, connPerLine)

    def takeSnapshot(self):
        return _pycarl.ConnectionMonitor_takeSnapshot(self)

    def takeSnapshot1D(self):
        return _pycarl.ConnectionMonitor_takeSnapshot1D(self)

    def testPrint(self, data):
        return _pycarl.ConnectionMonitor_testPrint(self, data)
ConnectionMonitor_swigregister = _pycarl.ConnectionMonitor_swigregister
ConnectionMonitor_swigregister(ConnectionMonitor)

class GroupMonitor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GroupMonitor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GroupMonitor, name)
    __repr__ = _swig_repr

    def __init__(self, groupMonitorCorePtr):
        this = _pycarl.new_GroupMonitor(groupMonitorCorePtr)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_GroupMonitor
    __del__ = lambda self: None

    def isRecording(self):
        return _pycarl.GroupMonitor_isRecording(self)

    def startRecording(self):
        return _pycarl.GroupMonitor_startRecording(self)

    def stopRecording(self):
        return _pycarl.GroupMonitor_stopRecording(self)

    def getRecordingTotalTime(self):
        return _pycarl.GroupMonitor_getRecordingTotalTime(self)

    def getRecordingLastStartTime(self):
        return _pycarl.GroupMonitor_getRecordingLastStartTime(self)

    def getRecordingStartTime(self):
        return _pycarl.GroupMonitor_getRecordingStartTime(self)

    def getRecordingStopTime(self):
        return _pycarl.GroupMonitor_getRecordingStopTime(self)

    def getPersistentData(self):
        return _pycarl.GroupMonitor_getPersistentData(self)

    def setPersistentData(self, persistentData):
        return _pycarl.GroupMonitor_setPersistentData(self, persistentData)

    def getDataVector(self):
        return _pycarl.GroupMonitor_getDataVector(self)

    def getPeakValueVector(self):
        return _pycarl.GroupMonitor_getPeakValueVector(self)

    def getPeakTimeVector(self):
        return _pycarl.GroupMonitor_getPeakTimeVector(self)

    def getSortedPeakValueVector(self):
        return _pycarl.GroupMonitor_getSortedPeakValueVector(self)

    def getSortedPeakTimeVector(self):
        return _pycarl.GroupMonitor_getSortedPeakTimeVector(self)
GroupMonitor_swigregister = _pycarl.GroupMonitor_swigregister
GroupMonitor_swigregister(GroupMonitor)

class SpikeMonitor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpikeMonitor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpikeMonitor, name)
    __repr__ = _swig_repr

    def __init__(self, spikeMonitorCorePtr):
        this = _pycarl.new_SpikeMonitor(spikeMonitorCorePtr)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_SpikeMonitor
    __del__ = lambda self: None

    def clear(self):
        return _pycarl.SpikeMonitor_clear(self)

    def getAllFiringRates(self):
        return _pycarl.SpikeMonitor_getAllFiringRates(self)

    def getAllFiringRatesSorted(self):
        return _pycarl.SpikeMonitor_getAllFiringRatesSorted(self)

    def getMaxFiringRate(self):
        return _pycarl.SpikeMonitor_getMaxFiringRate(self)

    def getMinFiringRate(self):
        return _pycarl.SpikeMonitor_getMinFiringRate(self)

    def getNeuronMeanFiringRate(self, neurId):
        return _pycarl.SpikeMonitor_getNeuronMeanFiringRate(self, neurId)

    def getNeuronNumSpikes(self, neurId):
        return _pycarl.SpikeMonitor_getNeuronNumSpikes(self, neurId)

    def getNumNeuronsWithFiringRate(self, min, max):
        return _pycarl.SpikeMonitor_getNumNeuronsWithFiringRate(self, min, max)

    def getNumSilentNeurons(self):
        return _pycarl.SpikeMonitor_getNumSilentNeurons(self)

    def getPercentNeuronsWithFiringRate(self, min, max):
        return _pycarl.SpikeMonitor_getPercentNeuronsWithFiringRate(self, min, max)

    def getPercentSilentNeurons(self):
        return _pycarl.SpikeMonitor_getPercentSilentNeurons(self)

    def getPopMeanFiringRate(self):
        return _pycarl.SpikeMonitor_getPopMeanFiringRate(self)

    def getPopStdFiringRate(self):
        return _pycarl.SpikeMonitor_getPopStdFiringRate(self)

    def getPopNumSpikes(self):
        return _pycarl.SpikeMonitor_getPopNumSpikes(self)

    def getSpikeVector2D(self):
        return _pycarl.SpikeMonitor_getSpikeVector2D(self)

    def isRecording(self):
        return _pycarl.SpikeMonitor_isRecording(self)

    def _print(self, printSpikeTimes=True):
        return _pycarl.SpikeMonitor__print(self, printSpikeTimes)

    def startRecording(self):
        return _pycarl.SpikeMonitor_startRecording(self)

    def stopRecording(self):
        return _pycarl.SpikeMonitor_stopRecording(self)

    def getRecordingTotalTime(self):
        return _pycarl.SpikeMonitor_getRecordingTotalTime(self)

    def getRecordingLastStartTime(self):
        return _pycarl.SpikeMonitor_getRecordingLastStartTime(self)

    def getRecordingStartTime(self):
        return _pycarl.SpikeMonitor_getRecordingStartTime(self)

    def getRecordingStopTime(self):
        return _pycarl.SpikeMonitor_getRecordingStopTime(self)

    def getPersistentData(self):
        return _pycarl.SpikeMonitor_getPersistentData(self)

    def setPersistentData(self, persistentData):
        return _pycarl.SpikeMonitor_setPersistentData(self, persistentData)

    def getMode(self):
        return _pycarl.SpikeMonitor_getMode(self)

    def setMode(self, mode=AER):
        return _pycarl.SpikeMonitor_setMode(self, mode)

    def setLogFile(self, logFileName):
        return _pycarl.SpikeMonitor_setLogFile(self, logFileName)
SpikeMonitor_swigregister = _pycarl.SpikeMonitor_swigregister
SpikeMonitor_swigregister(SpikeMonitor)

class SpikeGenerator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpikeGenerator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SpikeGenerator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycarl.delete_SpikeGenerator
    __del__ = lambda self: None

    def nextSpikeTime(self, s, grpId, i, currentTime, lastScheduledSpikeTime, endOfTimeSlice):
        return _pycarl.SpikeGenerator_nextSpikeTime(self, s, grpId, i, currentTime, lastScheduledSpikeTime, endOfTimeSlice)
SpikeGenerator_swigregister = _pycarl.SpikeGenerator_swigregister
SpikeGenerator_swigregister(SpikeGenerator)

class ConnectionGenerator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConnectionGenerator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ConnectionGenerator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycarl.delete_ConnectionGenerator
    __del__ = lambda self: None

    def connect(self, s, srcGrpId, i, destGrpId, j, weight, maxWt, delay, connected):
        return _pycarl.ConnectionGenerator_connect(self, s, srcGrpId, i, destGrpId, j, weight, maxWt, delay, connected)
ConnectionGenerator_swigregister = _pycarl.ConnectionGenerator_swigregister
ConnectionGenerator_swigregister(ConnectionGenerator)

class SpikeGeneratorFromVector(SpikeGenerator):
    __swig_setmethods__ = {}
    for _s in [SpikeGenerator]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SpikeGeneratorFromVector, name, value)
    __swig_getmethods__ = {}
    for _s in [SpikeGenerator]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SpikeGeneratorFromVector, name)
    __repr__ = _swig_repr

    def __init__(self, spkTimes):
        this = _pycarl.new_SpikeGeneratorFromVector(spkTimes)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_SpikeGeneratorFromVector
    __del__ = lambda self: None

    def nextSpikeTime(self, sim, grpId, nid, currentTime, lastScheduledSpikeTime, endOfTimeSlice):
        return _pycarl.SpikeGeneratorFromVector_nextSpikeTime(self, sim, grpId, nid, currentTime, lastScheduledSpikeTime, endOfTimeSlice)
SpikeGeneratorFromVector_swigregister = _pycarl.SpikeGeneratorFromVector_swigregister
SpikeGeneratorFromVector_swigregister(SpikeGeneratorFromVector)

class VisualStimulus(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VisualStimulus, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VisualStimulus, name)
    __repr__ = _swig_repr

    def __init__(self, fileName, wrapAroundEOF=True):
        this = _pycarl.new_VisualStimulus(fileName, wrapAroundEOF)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_VisualStimulus
    __del__ = lambda self: None

    def readFrameChar(self):
        return _pycarl.VisualStimulus_readFrameChar(self)

    def readFramePoisson(self, maxPoisson, minPoisson=0.0):
        return _pycarl.VisualStimulus_readFramePoisson(self, maxPoisson, minPoisson)

    def rewind(self):
        return _pycarl.VisualStimulus_rewind(self)

    def _print(self):
        return _pycarl.VisualStimulus__print(self)

    def getWidth(self):
        return _pycarl.VisualStimulus_getWidth(self)

    def getHeight(self):
        return _pycarl.VisualStimulus_getHeight(self)

    def getLength(self):
        return _pycarl.VisualStimulus_getLength(self)

    def getChannels(self):
        return _pycarl.VisualStimulus_getChannels(self)

    def getType(self):
        return _pycarl.VisualStimulus_getType(self)

    def getCurrentFrameChar(self):
        return _pycarl.VisualStimulus_getCurrentFrameChar(self)

    def getCurrentFramePoisson(self):
        return _pycarl.VisualStimulus_getCurrentFramePoisson(self)

    def getCurrentFrameNumber(self):
        return _pycarl.VisualStimulus_getCurrentFrameNumber(self)
VisualStimulus_swigregister = _pycarl.VisualStimulus_swigregister
VisualStimulus_swigregister(VisualStimulus)

class Grid3D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Grid3D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Grid3D, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycarl.new_Grid3D(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["numX"] = _pycarl.Grid3D_numX_set
    __swig_getmethods__["numX"] = _pycarl.Grid3D_numX_get
    if _newclass:
        numX = _swig_property(_pycarl.Grid3D_numX_get, _pycarl.Grid3D_numX_set)
    __swig_setmethods__["numY"] = _pycarl.Grid3D_numY_set
    __swig_getmethods__["numY"] = _pycarl.Grid3D_numY_get
    if _newclass:
        numY = _swig_property(_pycarl.Grid3D_numY_get, _pycarl.Grid3D_numY_set)
    __swig_setmethods__["numZ"] = _pycarl.Grid3D_numZ_set
    __swig_getmethods__["numZ"] = _pycarl.Grid3D_numZ_get
    if _newclass:
        numZ = _swig_property(_pycarl.Grid3D_numZ_get, _pycarl.Grid3D_numZ_set)
    __swig_setmethods__["distX"] = _pycarl.Grid3D_distX_set
    __swig_getmethods__["distX"] = _pycarl.Grid3D_distX_get
    if _newclass:
        distX = _swig_property(_pycarl.Grid3D_distX_get, _pycarl.Grid3D_distX_set)
    __swig_setmethods__["distY"] = _pycarl.Grid3D_distY_set
    __swig_getmethods__["distY"] = _pycarl.Grid3D_distY_get
    if _newclass:
        distY = _swig_property(_pycarl.Grid3D_distY_get, _pycarl.Grid3D_distY_set)
    __swig_setmethods__["distZ"] = _pycarl.Grid3D_distZ_set
    __swig_getmethods__["distZ"] = _pycarl.Grid3D_distZ_get
    if _newclass:
        distZ = _swig_property(_pycarl.Grid3D_distZ_get, _pycarl.Grid3D_distZ_set)
    __swig_setmethods__["offsetX"] = _pycarl.Grid3D_offsetX_set
    __swig_getmethods__["offsetX"] = _pycarl.Grid3D_offsetX_get
    if _newclass:
        offsetX = _swig_property(_pycarl.Grid3D_offsetX_get, _pycarl.Grid3D_offsetX_set)
    __swig_setmethods__["offsetY"] = _pycarl.Grid3D_offsetY_set
    __swig_getmethods__["offsetY"] = _pycarl.Grid3D_offsetY_get
    if _newclass:
        offsetY = _swig_property(_pycarl.Grid3D_offsetY_get, _pycarl.Grid3D_offsetY_set)
    __swig_setmethods__["offsetZ"] = _pycarl.Grid3D_offsetZ_set
    __swig_getmethods__["offsetZ"] = _pycarl.Grid3D_offsetZ_get
    if _newclass:
        offsetZ = _swig_property(_pycarl.Grid3D_offsetZ_get, _pycarl.Grid3D_offsetZ_set)
    __swig_setmethods__["N"] = _pycarl.Grid3D_N_set
    __swig_getmethods__["N"] = _pycarl.Grid3D_N_get
    if _newclass:
        N = _swig_property(_pycarl.Grid3D_N_get, _pycarl.Grid3D_N_set)
    __swig_destroy__ = _pycarl.delete_Grid3D
    __del__ = lambda self: None
Grid3D_swigregister = _pycarl.Grid3D_swigregister
Grid3D_swigregister(Grid3D)

class GroupNeuromodulatorInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GroupNeuromodulatorInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GroupNeuromodulatorInfo, name)
    __repr__ = _swig_repr
    __swig_setmethods__["baseDP"] = _pycarl.GroupNeuromodulatorInfo_baseDP_set
    __swig_getmethods__["baseDP"] = _pycarl.GroupNeuromodulatorInfo_baseDP_get
    if _newclass:
        baseDP = _swig_property(_pycarl.GroupNeuromodulatorInfo_baseDP_get, _pycarl.GroupNeuromodulatorInfo_baseDP_set)
    __swig_setmethods__["base5HT"] = _pycarl.GroupNeuromodulatorInfo_base5HT_set
    __swig_getmethods__["base5HT"] = _pycarl.GroupNeuromodulatorInfo_base5HT_get
    if _newclass:
        base5HT = _swig_property(_pycarl.GroupNeuromodulatorInfo_base5HT_get, _pycarl.GroupNeuromodulatorInfo_base5HT_set)
    __swig_setmethods__["baseACh"] = _pycarl.GroupNeuromodulatorInfo_baseACh_set
    __swig_getmethods__["baseACh"] = _pycarl.GroupNeuromodulatorInfo_baseACh_get
    if _newclass:
        baseACh = _swig_property(_pycarl.GroupNeuromodulatorInfo_baseACh_get, _pycarl.GroupNeuromodulatorInfo_baseACh_set)
    __swig_setmethods__["baseNE"] = _pycarl.GroupNeuromodulatorInfo_baseNE_set
    __swig_getmethods__["baseNE"] = _pycarl.GroupNeuromodulatorInfo_baseNE_get
    if _newclass:
        baseNE = _swig_property(_pycarl.GroupNeuromodulatorInfo_baseNE_get, _pycarl.GroupNeuromodulatorInfo_baseNE_set)
    __swig_setmethods__["decayDP"] = _pycarl.GroupNeuromodulatorInfo_decayDP_set
    __swig_getmethods__["decayDP"] = _pycarl.GroupNeuromodulatorInfo_decayDP_get
    if _newclass:
        decayDP = _swig_property(_pycarl.GroupNeuromodulatorInfo_decayDP_get, _pycarl.GroupNeuromodulatorInfo_decayDP_set)
    __swig_setmethods__["decay5HT"] = _pycarl.GroupNeuromodulatorInfo_decay5HT_set
    __swig_getmethods__["decay5HT"] = _pycarl.GroupNeuromodulatorInfo_decay5HT_get
    if _newclass:
        decay5HT = _swig_property(_pycarl.GroupNeuromodulatorInfo_decay5HT_get, _pycarl.GroupNeuromodulatorInfo_decay5HT_set)
    __swig_setmethods__["decayACh"] = _pycarl.GroupNeuromodulatorInfo_decayACh_set
    __swig_getmethods__["decayACh"] = _pycarl.GroupNeuromodulatorInfo_decayACh_get
    if _newclass:
        decayACh = _swig_property(_pycarl.GroupNeuromodulatorInfo_decayACh_get, _pycarl.GroupNeuromodulatorInfo_decayACh_set)
    __swig_setmethods__["decayNE"] = _pycarl.GroupNeuromodulatorInfo_decayNE_set
    __swig_getmethods__["decayNE"] = _pycarl.GroupNeuromodulatorInfo_decayNE_get
    if _newclass:
        decayNE = _swig_property(_pycarl.GroupNeuromodulatorInfo_decayNE_get, _pycarl.GroupNeuromodulatorInfo_decayNE_set)

    def __init__(self):
        this = _pycarl.new_GroupNeuromodulatorInfo()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycarl.delete_GroupNeuromodulatorInfo
    __del__ = lambda self: None
GroupNeuromodulatorInfo_swigregister = _pycarl.GroupNeuromodulatorInfo_swigregister
GroupNeuromodulatorInfo_swigregister(GroupNeuromodulatorInfo)

class ExpCurve(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ExpCurve, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ExpCurve, name)
    __repr__ = _swig_repr

    def __init__(self, _alphaPlus, _tauPlus, _alphaMinus, _tauMinus):
        this = _pycarl.new_ExpCurve(_alphaPlus, _tauPlus, _alphaMinus, _tauMinus)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["stdpCurve"] = _pycarl.ExpCurve_stdpCurve_set
    __swig_getmethods__["stdpCurve"] = _pycarl.ExpCurve_stdpCurve_get
    if _newclass:
        stdpCurve = _swig_property(_pycarl.ExpCurve_stdpCurve_get, _pycarl.ExpCurve_stdpCurve_set)
    __swig_setmethods__["alphaPlus"] = _pycarl.ExpCurve_alphaPlus_set
    __swig_getmethods__["alphaPlus"] = _pycarl.ExpCurve_alphaPlus_get
    if _newclass:
        alphaPlus = _swig_property(_pycarl.ExpCurve_alphaPlus_get, _pycarl.ExpCurve_alphaPlus_set)
    __swig_setmethods__["tauPlus"] = _pycarl.ExpCurve_tauPlus_set
    __swig_getmethods__["tauPlus"] = _pycarl.ExpCurve_tauPlus_get
    if _newclass:
        tauPlus = _swig_property(_pycarl.ExpCurve_tauPlus_get, _pycarl.ExpCurve_tauPlus_set)
    __swig_setmethods__["alphaMinus"] = _pycarl.ExpCurve_alphaMinus_set
    __swig_getmethods__["alphaMinus"] = _pycarl.ExpCurve_alphaMinus_get
    if _newclass:
        alphaMinus = _swig_property(_pycarl.ExpCurve_alphaMinus_get, _pycarl.ExpCurve_alphaMinus_set)
    __swig_setmethods__["tauMinus"] = _pycarl.ExpCurve_tauMinus_set
    __swig_getmethods__["tauMinus"] = _pycarl.ExpCurve_tauMinus_get
    if _newclass:
        tauMinus = _swig_property(_pycarl.ExpCurve_tauMinus_get, _pycarl.ExpCurve_tauMinus_set)
    __swig_destroy__ = _pycarl.delete_ExpCurve
    __del__ = lambda self: None
ExpCurve_swigregister = _pycarl.ExpCurve_swigregister
ExpCurve_swigregister(ExpCurve)

class TimingBasedCurve(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TimingBasedCurve, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TimingBasedCurve, name)
    __repr__ = _swig_repr

    def __init__(self, _alphaPlus, _tauPlus, _alphaMinus, _tauMinus, _gamma):
        this = _pycarl.new_TimingBasedCurve(_alphaPlus, _tauPlus, _alphaMinus, _tauMinus, _gamma)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["stdpCurve"] = _pycarl.TimingBasedCurve_stdpCurve_set
    __swig_getmethods__["stdpCurve"] = _pycarl.TimingBasedCurve_stdpCurve_get
    if _newclass:
        stdpCurve = _swig_property(_pycarl.TimingBasedCurve_stdpCurve_get, _pycarl.TimingBasedCurve_stdpCurve_set)
    __swig_setmethods__["alphaPlus"] = _pycarl.TimingBasedCurve_alphaPlus_set
    __swig_getmethods__["alphaPlus"] = _pycarl.TimingBasedCurve_alphaPlus_get
    if _newclass:
        alphaPlus = _swig_property(_pycarl.TimingBasedCurve_alphaPlus_get, _pycarl.TimingBasedCurve_alphaPlus_set)
    __swig_setmethods__["tauPlus"] = _pycarl.TimingBasedCurve_tauPlus_set
    __swig_getmethods__["tauPlus"] = _pycarl.TimingBasedCurve_tauPlus_get
    if _newclass:
        tauPlus = _swig_property(_pycarl.TimingBasedCurve_tauPlus_get, _pycarl.TimingBasedCurve_tauPlus_set)
    __swig_setmethods__["alphaMinus"] = _pycarl.TimingBasedCurve_alphaMinus_set
    __swig_getmethods__["alphaMinus"] = _pycarl.TimingBasedCurve_alphaMinus_get
    if _newclass:
        alphaMinus = _swig_property(_pycarl.TimingBasedCurve_alphaMinus_get, _pycarl.TimingBasedCurve_alphaMinus_set)
    __swig_setmethods__["tauMinus"] = _pycarl.TimingBasedCurve_tauMinus_set
    __swig_getmethods__["tauMinus"] = _pycarl.TimingBasedCurve_tauMinus_get
    if _newclass:
        tauMinus = _swig_property(_pycarl.TimingBasedCurve_tauMinus_get, _pycarl.TimingBasedCurve_tauMinus_set)
    __swig_setmethods__["gamma"] = _pycarl.TimingBasedCurve_gamma_set
    __swig_getmethods__["gamma"] = _pycarl.TimingBasedCurve_gamma_get
    if _newclass:
        gamma = _swig_property(_pycarl.TimingBasedCurve_gamma_get, _pycarl.TimingBasedCurve_gamma_set)
    __swig_destroy__ = _pycarl.delete_TimingBasedCurve
    __del__ = lambda self: None
TimingBasedCurve_swigregister = _pycarl.TimingBasedCurve_swigregister
TimingBasedCurve_swigregister(TimingBasedCurve)

class PulseCurve(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PulseCurve, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PulseCurve, name)
    __repr__ = _swig_repr

    def __init__(self, _betaLTP, _betaLTD, _lambda, _delta):
        this = _pycarl.new_PulseCurve(_betaLTP, _betaLTD, _lambda, _delta)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["stdpCurve"] = _pycarl.PulseCurve_stdpCurve_set
    __swig_getmethods__["stdpCurve"] = _pycarl.PulseCurve_stdpCurve_get
    if _newclass:
        stdpCurve = _swig_property(_pycarl.PulseCurve_stdpCurve_get, _pycarl.PulseCurve_stdpCurve_set)
    __swig_setmethods__["betaLTP"] = _pycarl.PulseCurve_betaLTP_set
    __swig_getmethods__["betaLTP"] = _pycarl.PulseCurve_betaLTP_get
    if _newclass:
        betaLTP = _swig_property(_pycarl.PulseCurve_betaLTP_get, _pycarl.PulseCurve_betaLTP_set)
    __swig_setmethods__["betaLTD"] = _pycarl.PulseCurve_betaLTD_set
    __swig_getmethods__["betaLTD"] = _pycarl.PulseCurve_betaLTD_get
    if _newclass:
        betaLTD = _swig_property(_pycarl.PulseCurve_betaLTD_get, _pycarl.PulseCurve_betaLTD_set)
    __swig_setmethods__["_lambda"] = _pycarl.PulseCurve__lambda_set
    __swig_getmethods__["_lambda"] = _pycarl.PulseCurve__lambda_get
    if _newclass:
        _lambda = _swig_property(_pycarl.PulseCurve__lambda_get, _pycarl.PulseCurve__lambda_set)
    __swig_setmethods__["delta"] = _pycarl.PulseCurve_delta_set
    __swig_getmethods__["delta"] = _pycarl.PulseCurve_delta_get
    if _newclass:
        delta = _swig_property(_pycarl.PulseCurve_delta_get, _pycarl.PulseCurve_delta_set)
    __swig_destroy__ = _pycarl.delete_PulseCurve
    __del__ = lambda self: None
PulseCurve_swigregister = _pycarl.PulseCurve_swigregister
PulseCurve_swigregister(PulseCurve)

class RangeWeight(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RangeWeight, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RangeWeight, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycarl.new_RangeWeight(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["min"] = _pycarl.RangeWeight_min_set
    __swig_getmethods__["min"] = _pycarl.RangeWeight_min_get
    if _newclass:
        min = _swig_property(_pycarl.RangeWeight_min_get, _pycarl.RangeWeight_min_set)
    __swig_setmethods__["init"] = _pycarl.RangeWeight_init_set
    __swig_getmethods__["init"] = _pycarl.RangeWeight_init_get
    if _newclass:
        init = _swig_property(_pycarl.RangeWeight_init_get, _pycarl.RangeWeight_init_set)
    __swig_setmethods__["max"] = _pycarl.RangeWeight_max_set
    __swig_getmethods__["max"] = _pycarl.RangeWeight_max_get
    if _newclass:
        max = _swig_property(_pycarl.RangeWeight_max_get, _pycarl.RangeWeight_max_set)
    __swig_destroy__ = _pycarl.delete_RangeWeight
    __del__ = lambda self: None
RangeWeight_swigregister = _pycarl.RangeWeight_swigregister
RangeWeight_swigregister(RangeWeight)

class RangeDelay(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RangeDelay, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RangeDelay, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycarl.new_RangeDelay(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["min"] = _pycarl.RangeDelay_min_set
    __swig_getmethods__["min"] = _pycarl.RangeDelay_min_get
    if _newclass:
        min = _swig_property(_pycarl.RangeDelay_min_get, _pycarl.RangeDelay_min_set)
    __swig_setmethods__["max"] = _pycarl.RangeDelay_max_set
    __swig_getmethods__["max"] = _pycarl.RangeDelay_max_get
    if _newclass:
        max = _swig_property(_pycarl.RangeDelay_max_get, _pycarl.RangeDelay_max_set)
    __swig_destroy__ = _pycarl.delete_RangeDelay
    __del__ = lambda self: None
RangeDelay_swigregister = _pycarl.RangeDelay_swigregister
RangeDelay_swigregister(RangeDelay)

class RadiusRF(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, RadiusRF, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, RadiusRF, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycarl.new_RadiusRF(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["radX"] = _pycarl.RadiusRF_radX_set
    __swig_getmethods__["radX"] = _pycarl.RadiusRF_radX_get
    if _newclass:
        radX = _swig_property(_pycarl.RadiusRF_radX_get, _pycarl.RadiusRF_radX_set)
    __swig_setmethods__["radY"] = _pycarl.RadiusRF_radY_set
    __swig_getmethods__["radY"] = _pycarl.RadiusRF_radY_get
    if _newclass:
        radY = _swig_property(_pycarl.RadiusRF_radY_get, _pycarl.RadiusRF_radY_set)
    __swig_setmethods__["radZ"] = _pycarl.RadiusRF_radZ_set
    __swig_getmethods__["radZ"] = _pycarl.RadiusRF_radZ_get
    if _newclass:
        radZ = _swig_property(_pycarl.RadiusRF_radZ_get, _pycarl.RadiusRF_radZ_set)
    __swig_destroy__ = _pycarl.delete_RadiusRF
    __del__ = lambda self: None
RadiusRF_swigregister = _pycarl.RadiusRF_swigregister
RadiusRF_swigregister(RadiusRF)

# This file is compatible with both classic and new-style classes.


