on:
  release: 
    types: [created]
name: release binaries
jobs:
  build_ubu22cuda11:
    # more appropriate permissions here? tinyurl.com/5725swh8
    permissions: write-all
    runs-on: ubu22cuda11
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run:  | 
        # modified gh runner's ./run-helper.sh.template for no 'sudo'
        docker build --no-cache --tag 'carlsim' .
        docker run --rm --gpus all -v /tmp/_gh_actions/:/tmp/uploads/ carlsim:latest \
          /bin/bash -c 'cp -r /tmp/binaries.zip /tmp/uploads && cp -r /tmp/pyCARL /tmp/uploads'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Publish distribution to PyPI
      env:
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        cd /tmp/_gh_actions/pyCARL
        python3 -m pip install wheel
        echo "[testpypi]\n  username = __token__ \n  password = $pypi_token" > ~/.pypirc
        twine upload dist/*

    - name: Upload binaries to gh release page
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/_gh_actions/binaries.zip
        asset_name: ubu18-22_cuda11.zip
        tag: ${{ github.ref }}
