on:
  release: 
    types: [created]
name: release binaries
jobs:
  build_ubu18cuda11:
    # more appropriate permissions here? tinyurl.com/5725swh8
    permissions: write-all
    runs-on: ubu18cuda11 
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run:  | 
             sudo docker build --tag 'carlsim' .
             sudo docker run --gpus all --rm -v /tmp/_gh_actions_carl:/tmp carlsim
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/_gh_actions_carl/binaries.zip
        asset_name: ubu18-22_cuda11.zip
        tag: ${{ github.ref }}
