on:
  release: 
    types: [created]
name: release binaries
jobs:
  build_ubu22cuda11:
    # more appropriate permissions here? tinyurl.com/5725swh8
    permissions: write-all
    runs-on: ubu22cuda11
    steps:
    - name: Install setuptools
      run: python3 -m pip install wheel
    - uses: actions/checkout@v3
    - name: Build
      run:  | 
        # modified gh runner's ./run-helper.sh.template for no 'sudo'
        docker build --tag 'carlsim' .
        docker run --gpus all --rm -v /tmp/_gh_actions_carl:/tmp carlsim
        cd /tmp/_gh_actions_carl/carlsim/pyCARL
        
    - name: Publish distribution to PyPI
      env:
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "[testpypi]\n  username = __token__ \n  password = $pypi_token" > ~/.pypirc
        twine upload dist/*

    - name: Upload binaries to gh release page
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: /tmp/_gh_actions_carl/binaries.zip
        asset_name: ubu18-22_cuda11.zip
        tag: ${{ github.ref }}
