name: CMake

on:
  push:
    branches: [ "main" ] 
  #pull_request:
    #branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run:  | 
            mkdir ${{github.workspace}}/build
            cd ${{github.workspace}}/build
            cmake -DCMAKE_INSTALL_PREFIX=/tmp/carlsim6 \
                  -DCMAKE_BUILD_TYPE=Release .. \
                  -DCARLSIM_NO_CUDA=ON \
                  -DCARLSIM_TEST=ON \
                  -DCARLSIM_PYCARL=OFF
            make -j$(nproc) install
            
    - name: Run tests
      run:  | 
            echo $PWD
            ./carlsim/test/carlsim-tests
            ./carlsim/test6/carlsim-tests6
            ./carlsim/testadv/carlsim-testsadv
