name: CMake

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run:  | 
            mkdir ${{github.workspace}}/build
            cd ${{github.workspace}}/build
            cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
            mkdir ${{github.workspace}}/build
            cd ${{github.workspace}}/build
            cmake -DCMAKE_INSTALL_PREFIX=/home/user1/carlsim6 -DCMAKE_BUILD_TYPE=Release ../.
            make install
            # cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

