on:
  release: 
    types: [created]
name: Handle Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run:  | 
            mkdir ${{github.workspace}}/build
            cd ${{github.workspace}}/build
            cmake -DCMAKE_INSTALL_PREFIX=/tmp/carlsim6 \
                  -DCMAKE_BUILD_TYPE=Release .. \
                  -DCARLSIM_NO_CUDA=ON \
                  -DCARLSIM_TEST=OFF \
                  -DCARLSIM_PYCARL=OFF
            make install
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: projects/hello_world/hello_world
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
