on:
  release: 
    types: [created]
name: Handle Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run:  | 
            mkdir ${{github.workspace}}/build
            cd ${{github.workspace}}/build
            cmake -DCMAKE_INSTALL_PREFIX=/tmp/carlsim6 \
                  -DCMAKE_BUILD_TYPE=Release .. \
                  -DCARLSIM_NO_CUDA=ON \
                  -DCARLSIM_TEST=OFF \
                  -DCARLSIM_PYCARL=OFF
            make install
  generate:
    name: Upload the artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: './projects/hello_world/hello_world'
